name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: create external dir
      run: mkdir -p external/

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive  
    
    - name: Set up environment
      run: |
        sudo apt-get update && sudo apt-get install -y cmake build-essential
    
    - name: Build and run tests
      run: |
        ls external
        cmake -B build/ -DCMAKE_BUILD_TYPE=Debug
        cd build/
        make
        cd ..
        ./build/googletests  # Replace with your actual test executable name
