jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Create folder
      run: mkdir -p external/

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Initialize and update submodules (if needed)
      run: git submodule update --init --recursive
    
   
    
    - name: Set up environment
      run: |
        sudo apt-get update && sudo apt-get install -y cmake build-essential
    
    - name: Build and run tests
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Debug
        cd build
        make
        cd ..
        ./build/symbolic
